name: Manifest Check
on:
  push:
    branches:
      - main
      - 'release/**'
    paths:
      - 'go.mod'
  pull_request:
    branches:
      - main
      - 'release/**'
    paths:
      - 'go.mod'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  ManifestCheck:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - run: make downloader
      - run: echo $ModModified
      - run: ./build/bin/downloader manifest-verify --chain bsc
      - run: ./build/bin/downloader manifest-verify --chain chapel
